// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace TextBoxScssNamespace {
  export interface ITextBoxScss {
    input: string;
    "input-not-valid": string;
    inputNotValid: string;
    label: string;
    "text-box-container": string;
    textBoxContainer: string;
  }
}

declare const TextBoxScssModule: TextBoxScssNamespace.ITextBoxScss;

export = TextBoxScssModule;
