// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace AboutScssNamespace {
  export interface IAboutScss {
    readme: string;
  }
}

declare const AboutScssModule: AboutScssNamespace.IAboutScss;

export = AboutScssModule;
