// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace DropdownScssNamespace {
  export interface IDropdownScss {
    "dropdown-container": string;
    dropdownContainer: string;
    label: string;
    select: string;
    "select-not-valid": string;
    selectNotValid: string;
  }
}

declare const DropdownScssModule: DropdownScssNamespace.IDropdownScss;

export = DropdownScssModule;
