// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace AppScssNamespace {
  export interface IAppScss {
    container: string;
  }
}

declare const AppScssModule: AppScssNamespace.IAppScss;

export = AppScssModule;
