// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace TableScssNamespace {
  export interface ITableScss {
    next: string;
    "next-link": string;
    nextLink: string;
    "page-li": string;
    "page-li-link": string;
    pageLi: string;
    pageLiLink: string;
    "pagination-container": string;
    "pagination-link-active": string;
    paginationContainer: string;
    paginationLinkActive: string;
    previous: string;
    "previous-link": string;
    previousLink: string;
    "table-container": string;
    tableContainer: string;
  }
}

declare const TableScssModule: TableScssNamespace.ITableScss;

export = TableScssModule;
