// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace MenuScssNamespace {
  export interface IMenuScss {
    image: string;
    navigation: string;
    ul: string;
  }
}

declare const MenuScssModule: MenuScssNamespace.IMenuScss;

export = MenuScssModule;
