// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace StylesSharedScssNamespace {
  export interface IStylesSharedScss {
    button: string;
    dropdown: string;
    "form-container": string;
    formContainer: string;
    "search-container": string;
    searchContainer: string;
    stars: string;
    "text-box": string;
    textBox: string;
  }
}

declare const StylesSharedScssModule: StylesSharedScssNamespace.IStylesSharedScss;

export = StylesSharedScssModule;
